//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeteriaUnapec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion_Articulos
    {
        public int No_Factura { get; set; }
        public int Id_Empleado { get; set; }
        public int Id_Articulo { get; set; }
        public System.DateTime Fecha_Venta { get; set; }
        public decimal Monto_Articulo { get; set; }
        public int Unidades_Vendidas { get; set; }
        public string Comentario { get; set; }
        public bool Activo { get; set; }
        public int Id_User { get; set; }
    
        public virtual ARTICULOS ARTICULOS { get; set; }
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
