//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeteriaUnapec
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAFETERIAEntities1 : DbContext
    {
        public CAFETERIAEntities1()
            : base("name=CAFETERIAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTICULOS> ARTICULOS { get; set; }
        public virtual DbSet<CAFETERIAS> CAFETERIAS { get; set; }
        public virtual DbSet<CAMPUS> CAMPUS { get; set; }
        public virtual DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual DbSet<Facturacion_Articulos> Facturacion_Articulos { get; set; }
        public virtual DbSet<MARCAS> MARCAS { get; set; }
        public virtual DbSet<PROVEEDORES> PROVEEDORES { get; set; }
        public virtual DbSet<Tipo_usuarios> Tipo_usuarios { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
