//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeteriaUnapec
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTICULOS()
        {
            this.Facturacion_Articulos = new HashSet<Facturacion_Articulos>();
        }
    
        public int Id_Articulo { get; set; }
        public string Descripcion { get; set; }
        public int Id_Marca { get; set; }
        public decimal Costo { get; set; }
        public int Id_Proveedor { get; set; }
        public int Existencia { get; set; }
        public bool Activo { get; set; }
    
        public virtual MARCAS MARCAS { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturacion_Articulos> Facturacion_Articulos { get; set; }
    }
}
