//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeteriaUnapec
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAFETERIAS
    {
        public int Id_Cafeteria { get; set; }
        public string Descripción { get; set; }
        public int Id_Campus { get; set; }
        public string Encargado { get; set; }
        public bool Activo { get; set; }
    
        public virtual CAMPUS CAMPUS { get; set; }
    }
}
